server:
  port: 8010
  context-path: /mail

spring:
  data:
    mongodb:
      host: ${MAIL_MONGO:localhost}
      username: user
      password: ${PASS_MONGO:test}
      database: mail
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    username: savemaker.app
    password: uypwxzsaumgimzyo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  oauth2:
    client:
      clientId: mail
      clientSecret: ${MAIL_AUTH_PASS:mail}
      accessTokenUri: ${AUTH_SERVER_URL:http://localhost:5000/uaa/user}
      grant-type: client_credentials
      scope: server

mail:
  send:
    unsent:
      cron: 0 6 17 1/1 * ?
      max: 10